// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqxCtdeVR3YeTWUptoghR7ArCH6nGMH9o',
    appId: '1:266681401852:web:43768cd988307fdd66b279',
    messagingSenderId: '266681401852',
    projectId: 'newprojectwireless',
    authDomain: 'newprojectwireless.firebaseapp.com',
    storageBucket: 'newprojectwireless.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAILvWOurJDdAD8flC60xrb0APyMmIY6hI',
    appId: '1:266681401852:android:d3f58a0c2b31079c66b279',
    messagingSenderId: '266681401852',
    projectId: 'newprojectwireless',
    storageBucket: 'newprojectwireless.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCB9wprFySyEyT3q7cEoKgkeoZdyQRfdss',
    appId: '1:266681401852:ios:e844e24dd4bcaabb66b279',
    messagingSenderId: '266681401852',
    projectId: 'newprojectwireless',
    storageBucket: 'newprojectwireless.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCB9wprFySyEyT3q7cEoKgkeoZdyQRfdss',
    appId: '1:266681401852:ios:e844e24dd4bcaabb66b279',
    messagingSenderId: '266681401852',
    projectId: 'newprojectwireless',
    storageBucket: 'newprojectwireless.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqxCtdeVR3YeTWUptoghR7ArCH6nGMH9o',
    appId: '1:266681401852:web:77b82698afc1a52c66b279',
    messagingSenderId: '266681401852',
    projectId: 'newprojectwireless',
    authDomain: 'newprojectwireless.firebaseapp.com',
    storageBucket: 'newprojectwireless.appspot.com',
  );

}